food_proj/food/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as cbviews
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from .views import ItemViewSet,LowpriseViewSet

router=routers.SimpleRouter()
router.register('foodapi',ItemViewSet,basename='foodapi')
router.register('lessprice',LowpriseViewSet,basename='lessprice')


app_name='food'
urlpatterns=[
path('',views.home,name='home'),
path('<int:item_id>',views.details,name='details'),
path('create_item',views.create_item,name='create_item'),
path('update/<int:id>',views.update,name='update'),
path('delete/<int:pk>',views.delete,name='delete'),
path('register',views.register,name='register'),
path('login',cbviews.LoginView.as_view(template_name='login.html'),name='login'),
path('logout',views.logout,name='logout'),
path('profile',views.profilepage,name='profile'),
path('',include(router.urls)),

]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_proj/food_proj/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),

]

food_proj/movies/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework import routers
from .views import MovieViewSet,ActionViewSet,ComedyViewSet


router=routers.SimpleRouter()
router.register('movies',MovieViewSet,basename='movies')
router.register('action',ActionViewSet,basename='action')
router.register('comedy',ComedyViewSet,basename='comedy')
urlpatterns = [
    path('admin2/', admin.site.urls),
    path('',include(router.urls)),
    # Include other URLs specific to the 'movies' app here
]

food_proj/food/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class item(models.Model):
   
   
    item_name=models.CharField(max_length=220)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField(default=0)
    item_image=models.CharField(max_length=1000,default='https://lh3.googleusercontent.com/RLo2nYsnoSNTVTCZoiRslZwFtt3FFCFZZG1wVPTAVgZ60P5thfiEWMuGesDHqOff983Z=w170')


    def __str__(self):
     return self.item_name

class profile(models.Model):
   user=models.OneToOneField(User,on_delete=models.CASCADE)
   image_field=models.ImageField(default='profile.jpg',upload_to='profile_pictures')  
   location=models.CharField(max_length=250)


   def __str__(self):
      return self.user.username 
   

food_proj/movies/models.py
from django.db import models

# Create your models here.

class movie(models.Model):
    name=models.CharField(max_length=200)
    duration=models.FloatField()
    rating=models.FloatField()
    typ=models.CharField(max_length=200,default='action')
   


    def __str__(self):
        return self.name

food_proj/food/forms.py
from django import forms
from .models import item
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class item_form(forms.ModelForm):
    class Meta:
        model=item
        fields='__all__'

class registration_form(UserCreationForm):
   

    class Meta:
        model=User
        fields=['username','email','password1','password2']

   

food_proj/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import item
from .forms import item_form
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import registration_form
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from .serializers import ItemSerializer
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    
    item_list=item.objects.all()
    item_type=request.GET.get('item')
   

    if item_type is not None:

        item_list=item_list.filter(item_name__icontains=item_type)

        if  not item_list.exists():
            return render(request,'noitem.html') 
   
    paginator=Paginator(item_list,3)
    page=request.GET.get('page')
    item_list=paginator.get_page(page)
    context={
        'items':item_list
    }

    return render(request,'home.html',context)


def details(request,item_id):
    snack=item.objects.get(pk=item_id)
    context={
        'snack':snack
    }

    return render(request,'details.html',context)
@login_required
def create_item(request):
    form=item_form(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:home')
    
    return render(request,'item_create.html',{'form':form})


def update(request,id):
    itm=item.objects.get(id=id)
    form=item_form(request.POST or None,instance=itm)

    if form.is_valid():
        form.save()
        return redirect('food:home')
    return render(request,'item_create.html',{'form':form,'itm':itm})

def delete(request,pk):
    itm=item.objects.get(id=pk)
    if request.method=='POST':
     itm.delete()
     return redirect('food:home')
    return render(request,'delete.html',{'itm':itm})

def register(request):
    if request.method=='POST':
     form=registration_form(request.POST)
     if form.is_valid():    
         form.save()
         username=form.cleaned_data.get('username')
         messages.success(request,f'Welcome {username}... You successfully Login')
         return redirect('food:login')
    else:
       
        form=registration_form() 

    return render(request,'register.html',{'form':form})   


def logout(request):
       if request.method=='POST':
        auth.logout(request)
        return redirect('food:home')
       
       return render(request,'logout.html')
@login_required
def profilepage(request):
    return render(request,'profile.html')

class ItemViewSet(viewsets.ModelViewSet):
    queryset=item.objects.all()
    serializer_class=ItemSerializer 

class LowpriseViewSet(viewsets.ModelViewSet):
    queryset=item.objects.filter(item_price__lt=20) 
    serializer_class=ItemSerializer   
   

food_proj/movies/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import movie
from .serializers import MovieSerializer

class MovieViewSet(viewsets.ModelViewSet):
    queryset=movie.objects.all()
    serializer_class=MovieSerializer

class ActionViewSet(viewsets.ModelViewSet):
     queryset=movie.objects.filter(typ='action') 
     serializer_class=MovieSerializer   
class ComedyViewSet(viewsets.ModelViewSet):
     queryset=movie.objects.filter(typ='comedy') 
     serializer_class=MovieSerializer   

food_proj/food/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}

        <h2>Are you sure to delete {{itm.item_name}}</h2>
        <button type="submit" class="btn btn-secondary">confirm</button>
    
    </form>
    
</body>
</html>

food_proj/food/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <h1>{{snack.item_name}}</h1>
    <h2>{{snack.item_desc}}</h2>
    <h2>{{snack.item_price}}</h2>

    <a href="{% url 'food:delete' snack.id %}" class="btn btn-danger">Delete</a>
    
</body>
</html>
               
            

food_proj/food/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark  ">
        <a href="#"  class="navbar-brand">FOODII APP</a>
        <div class="container-fluid">
            <ul class="navbar-nav ">
            <li class="nav-item">
           <a href="{% url 'food:create_item' %}" class="nav-link">Add-Item</a>
           </li>
           <li class="nav-item" >
            {% if user.is_authenticated %}
              <a href="{% url 'food:logout' %}" class="nav-link">logout</a>
             
            {% else %}  
            <a href="{% url 'food:login' %}" class="nav-link">logIn</a>
            {% endif %}
            </li>
            <li class="nav-item">
                <a href="{% url 'food:profile' %}" class="nav-link">profile</a>
                </li>
                
                <li class="nav-item">
                    <a href="{% url 'food:register' %}" class="nav-link">Register</a>
                </li>
         
               
        </ul>
        </div>
    </nav>
    <!-- {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %} -->
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}


    <p id="text-message" class="alert alert-success float-center text-center text-message" ><i class="fa fa-check" aria-hidden="true"></i>&nbsp; {{message}}</p>

    {% endif %}
    {% endfor %}

    <form action="" method="GET">
        <input type="search" name="item" class="btn btn-light mt-2">
        <button type="submit" class="btn btn-warning mt-2">Search</button>
    </form>
  
    {% for item in items %}
    <div class="row">
        <div class="col-md-3 offset-md-2 mt-3">
            <img class="card" height="150px" width="100px" src="{{ item.item_image }}">

        </div>
        <div class="col-md-4 mt-3">

            <h2>{{item.item_name}}</h2>
            <h3>{{item.item_desc}}</h3>
            <h4>${{item.item_price}}</h4><br><br>
            


        </div>
        <div class="col-md-2">
            <a href="{% url 'food:details' item.id %}" class="btn btn-success m-3">Details</a>
            <a href="{% url 'food:update' item.id %}" class="btn btn-primary m-3">Edit</a>
        </div>
        
    </div>

    {% endfor %}
    <footer>
    {% if items.has_previous %}
    <a class="btn btn-primary" href="?page=1">First</a>
    <a class="btn btn-primary" href="?page={{ items.previous_page_number }}">Previous</a>
    {% endif %}

    <b>Page:</b>{{ items.number }} of {{ items.paginator.num_pages }}

    {% if items.has_next %}
    <a class="btn btn-primary" href="?page={{ items.next_page_number }}">Next</a>
    <a class="btn btn-primary" href="?page={{ items.paginator.num_pages }}">Last</a>
    {% endif %}

</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'myjs.js' %}"></script>

</body>
</html>

food_proj/food/templates/item_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-4">
            <div class="card bg-info">
                <div class="card-header ">
                    <div class="card-title text-center">
                        ADD-ITEM

                    </div>

                </div>
                <div class="card-body bg-black">
                <form action="" method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        <div class="text-white">
                        {{field.name}}: <br>
            
                          {{ field }}
                        </div>

                    </div>
                    
                   {% endfor %}
                <div class="text-center m-2">
                   <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
                
            </form>

            </div>

        </div>

    </div>
 



   

</div>



</body>
</html>

food_proj/food/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white text-center bg-info">
                        <div class="card-title">
                        Login
                        </div>
    
                    </div>
                    <div class="card-body bg-black">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                            
                            <div class="form-group">
                                <div class="text-white m-2">
                                {{field.name}} :
                                {{field}}
                                 </div>
                                
                            </div>
                               

                            {% endfor %}
                            <div class="text-center">
                            <button type="submit" class="btn btn-success m-2">LOGIN</button>
                            </div>
                        </form>
    
                    </div>
                </div>
            </div>
        </div>
    
    </div>
    
    
    
</body>
</html>

food_proj/food/templates/logout.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<form action="" method="POST">
    {% csrf_token %}
<h2>Are you want to Logout {{user}}</h2>
<button type="submit" class="btn btn-danger mt-6" style="align-items: center;">Logout</button>
</form>

food_proj/food/templates/noitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>Document</title>
</head>
<body>
    <h1>No Item Available Please select Another Item😍</h1>
    <a href="{% url 'food:home' %}"><button class="btn btn-success">Home</button></a>
</body>
</html>

food_proj/food/templates/profile.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<h1>Hii I'm {{user.username}}</h1>
<img class='image' src="{{ user.profile.image_field.url }}" style="width: 300px; height: auto;"><br>

<a href="{% url 'food:home' %}"><button class="btn btn-secondary mt-5">Homepage</button></a>

food_proj/food/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-4">
                <div class="card">
                    <div class="card-header bg-info">
                        <div class="card-title text-center">
                        Register
                        </div>
                    </div>
              
                <div class="card-body bg-black">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form m-2">
                        <div class="text-white">
                        {{field.label}} :
                        <br>
                        {{field}}
                       </div>
                        </div>
                        {% endfor %}
                        <div class="text-center m-2">
                        <button type="submit" class="btn btn-success">SIGNIN</button>
                       </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
    
</body>
</html>